### ISSUE TITLE
Targets not showing

### ISSUE THREAD

**Issue by iRoachie** [AtomBuild/atom-build-gulp#9] opened 2016-02-16 20:49 UTC
I'm only seeing the Gulp:default build target.

**Comment by noseglid** [comment] 2016-02-20 11:17
Do you have `gulp` installed with the project (i.e. in `node_modules`)?

**Comment by iRoachie** [comment] 2016-02-20 18:26
Yea

**Comment by noseglid** [comment] 2016-02-20 19:40
So, steps to reproduce? It [works well for me](https://i.github-camo.com/8bc5c914b4c68fe77609704bed51020b07369765/68747470733a2f2f6e6f7365676c69642e6769746875622e696f2f746172676574732e676966).

**Comment by iRoachie** [comment] 2016-02-20 19:56
I installed the atom-build package, then install atom-build-gulp. When I used the F7 shortcut to show targets, it only shows default in the options.

<img width="1022" alt="screen shot 2016-02-20 at 3 56 15 pm" src="https://cloud.githubusercontent.com/assets/5962998/13198855/83f0da34-d7ea-11e5-8dd1-a297c079af0c.png">

**Comment by noseglid** [comment] 2016-02-20 20:08
That _should_ work. There has to be something more going on. What if you restart Atom? If that doesn't help try and debug the `parser-task.js` and see where it fails.

**Comment by iRoachie** [comment] 2016-02-20 20:31
It's failing in the try catch. 

const gulp = require(`${path}/node_modules/gulp`);

The gulp.tasks object is empty

**Comment by iRoachie** [comment] 2016-02-20 21:50
Error thrown 

```
The `libsass` binding was not found in /Users/kyle/Developer/markev-couriers/node_modules/node-sass/vendor/darwin-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
```

**Comment by noseglid** [comment] 2016-02-21 08:42
dupe of #8

**Closed as completed by noseglid** 2016-02-21 08:42 UTC
